import { neutralDark, neutralLight } from './shared'
import { amber, indigo, gray, emerald, orange, red, sky, yellow, white } from '../colors'

import type { Theme } from '@/types'

type ColorPalette = Theme['colors']

export const amberLight: ColorPalette = {
    ...neutralLight,
    primary: amber[500],
    onPrimary: white,
    primaryHover: amber[600],
    primaryActive: amber[700],
    primarySubtle: amber[50],
    secondary: gray[500],
    onSecondary: white,
    secondaryHover: gray[600],
    secondaryActive: gray[700],
    secondarySubtle: gray[100],
    accent: indigo[500],
    onAccent: white,
    accentHover: indigo[600],
    accentSubtle: indigo[50],
    borderFocus: amber[500],
    success: emerald[500],
    onSuccess: white,
    successHover: emerald[600],
    successSubtle: emerald[50],
    warning: orange[500],
    onWarning: white,
    warningHover: orange[600],
    warningSubtle: orange[50],
    error: red[500],
    onError: white,
    errorHover: red[600],
    errorSubtle: red[50],
    info: sky[500],
    onInfo: white,
    infoHover: sky[600],
    infoSubtle: sky[50],
    link: amber[600],
    linkHover: amber[700],
    linkVisited: yellow[700],
    focus: amber[500],
}

export const amberDark: ColorPalette = {
    ...neutralDark,
    primary: amber[400],
    onPrimary: amber[950],
    primaryHover: amber[300],
    primaryActive: amber[500],
    primarySubtle: amber[900],
    secondary: gray[400],
    onSecondary: gray[900],
    secondaryHover: gray[300],
    secondaryActive: gray[200],
    secondarySubtle: gray[800],
    accent: indigo[400],
    onAccent: indigo[950],
    accentHover: indigo[300],
    accentSubtle: indigo[900],
    borderFocus: amber[400],
    success: emerald[400],
    onSuccess: emerald[950],
    successHover: emerald[300],
    successSubtle: emerald[900],
    warning: orange[400],
    onWarning: orange[950],
    warningHover: orange[300],
    warningSubtle: orange[900],
    error: red[400],
    onError: red[950],
    errorHover: red[300],
    errorSubtle: red[900],
    info: sky[400],
    onInfo: sky[950],
    infoHover: sky[300],
    infoSubtle: sky[900],
    link: amber[400],
    linkHover: amber[300],
    linkVisited: yellow[400],
    focus: amber[400],
}

