import { neutralDark, neutralLight } from './shared'
import { cyan, rose, gray, emerald, amber, red, blue, teal, white } from '../colors'

import type { BaseTheme } from '@/types'

type ColorPalette = BaseTheme['colors']

export const cyanLight: ColorPalette = {
    ...neutralLight,
    primary: cyan[500],
    onPrimary: white,
    primaryHover: cyan[600],
    primaryActive: cyan[700],
    primarySubtle: cyan[50],
    secondary: gray[500],
    onSecondary: white,
    secondaryHover: gray[600],
    secondaryActive: gray[700],
    secondarySubtle: gray[100],
    accent: rose[500],
    onAccent: white,
    accentHover: rose[600],
    accentSubtle: rose[50],
    borderFocus: cyan[500],
    success: emerald[500],
    onSuccess: white,
    successHover: emerald[600],
    successSubtle: emerald[50],
    warning: amber[500],
    onWarning: white,
    warningHover: amber[600],
    warningSubtle: amber[50],
    error: red[500],
    onError: white,
    errorHover: red[600],
    errorSubtle: red[50],
    info: blue[500],
    onInfo: white,
    infoHover: blue[600],
    infoSubtle: blue[50],
    link: cyan[500],
    linkHover: cyan[600],
    linkVisited: teal[600],
    focus: cyan[500],
}

export const cyanDark: ColorPalette = {
    ...neutralDark,
    primary: cyan[400],
    onPrimary: cyan[950],
    primaryHover: cyan[300],
    primaryActive: cyan[500],
    primarySubtle: cyan[900],
    secondary: gray[400],
    onSecondary: gray[900],
    secondaryHover: gray[300],
    secondaryActive: gray[200],
    secondarySubtle: gray[800],
    accent: rose[400],
    onAccent: rose[950],
    accentHover: rose[300],
    accentSubtle: rose[900],
    borderFocus: cyan[400],
    success: emerald[400],
    onSuccess: emerald[950],
    successHover: emerald[300],
    successSubtle: emerald[900],
    warning: amber[400],
    onWarning: amber[950],
    warningHover: amber[300],
    warningSubtle: amber[900],
    error: red[400],
    onError: red[950],
    errorHover: red[300],
    errorSubtle: red[900],
    info: blue[400],
    onInfo: blue[950],
    infoHover: blue[300],
    infoSubtle: blue[900],
    link: cyan[400],
    linkHover: cyan[300],
    linkVisited: teal[400],
    focus: cyan[400],
}

