import { neutralDark, neutralLight } from './shared'
import { emerald, amber, gray, green, orange, red, sky, teal, white } from '../colors'

import type { BaseTheme } from '@/types'

type ColorPalette = BaseTheme['colors']

export const emeraldLight: ColorPalette = {
    ...neutralLight,
    primary: emerald[500],
    onPrimary: white,
    primaryHover: emerald[600],
    primaryActive: emerald[700],
    primarySubtle: emerald[50],
    secondary: gray[500],
    onSecondary: white,
    secondaryHover: gray[600],
    secondaryActive: gray[700],
    secondarySubtle: gray[100],
    accent: amber[500],
    onAccent: white,
    accentHover: amber[600],
    accentSubtle: amber[50],
    borderFocus: emerald[500],
    success: green[500],
    onSuccess: white,
    successHover: green[600],
    successSubtle: green[50],
    warning: orange[500],
    onWarning: white,
    warningHover: orange[600],
    warningSubtle: orange[50],
    error: red[500],
    onError: white,
    errorHover: red[600],
    errorSubtle: red[50],
    info: sky[500],
    onInfo: white,
    infoHover: sky[600],
    infoSubtle: sky[50],
    link: emerald[500],
    linkHover: emerald[600],
    linkVisited: teal[500],
    focus: emerald[500],
}

export const emeraldDark: ColorPalette = {
    ...neutralDark,
    primary: emerald[400],
    onPrimary: emerald[950],
    primaryHover: emerald[300],
    primaryActive: emerald[500],
    primarySubtle: emerald[900],
    secondary: gray[400],
    onSecondary: gray[900],
    secondaryHover: gray[300],
    secondaryActive: gray[200],
    secondarySubtle: gray[800],
    accent: amber[400],
    onAccent: amber[950],
    accentHover: amber[300],
    accentSubtle: amber[900],
    borderFocus: emerald[400],
    success: green[400],
    onSuccess: green[950],
    successHover: green[300],
    successSubtle: green[900],
    warning: orange[400],
    onWarning: orange[950],
    warningHover: orange[300],
    warningSubtle: orange[900],
    error: red[400],
    onError: red[950],
    errorHover: red[300],
    errorSubtle: red[900],
    info: sky[400],
    onInfo: sky[950],
    infoHover: sky[300],
    infoSubtle: sky[900],
    link: emerald[400],
    linkHover: emerald[300],
    linkVisited: teal[400],
    focus: emerald[400],
}

