import { neutralDark, neutralLight } from './shared'
import { gray, indigo, emerald, amber, red, blue, white } from '../colors'

import type { Theme } from '@/types'

type ColorPalette = Theme['colors']

export const grayLight: ColorPalette = {
    ...neutralLight,
    primary: gray[900],
    onPrimary: white,
    primaryHover: gray[800],
    primaryActive: gray[950],
    primarySubtle: gray[100],
    secondary: gray[500],
    onSecondary: white,
    secondaryHover: gray[600],
    secondaryActive: gray[700],
    secondarySubtle: gray[100],
    accent: indigo[500],
    onAccent: white,
    accentHover: indigo[600],
    accentSubtle: indigo[50],
    borderFocus: gray[900],
    success: emerald[500],
    onSuccess: white,
    successHover: emerald[600],
    successSubtle: emerald[50],
    warning: amber[500],
    onWarning: white,
    warningHover: amber[600],
    warningSubtle: amber[50],
    error: red[500],
    onError: white,
    errorHover: red[600],
    errorSubtle: red[50],
    info: blue[500],
    onInfo: white,
    infoHover: blue[600],
    infoSubtle: blue[50],
    link: gray[900],
    linkHover: gray[700],
    linkVisited: gray[600],
    focus: gray[900],
}

export const grayDark: ColorPalette = {
    ...neutralDark,
    primary: gray[50],
    onPrimary: gray[900],
    primaryHover: gray[100],
    primaryActive: gray[200],
    primarySubtle: gray[800],
    secondary: gray[400],
    onSecondary: gray[900],
    secondaryHover: gray[300],
    secondaryActive: gray[200],
    secondarySubtle: gray[800],
    accent: indigo[400],
    onAccent: indigo[950],
    accentHover: indigo[300],
    accentSubtle: indigo[900],
    borderFocus: gray[50],
    success: emerald[400],
    onSuccess: emerald[950],
    successHover: emerald[300],
    successSubtle: emerald[900],
    warning: amber[400],
    onWarning: amber[950],
    warningHover: amber[300],
    warningSubtle: amber[900],
    error: red[400],
    onError: red[950],
    errorHover: red[300],
    errorSubtle: red[900],
    info: blue[400],
    onInfo: blue[950],
    infoHover: blue[300],
    infoSubtle: blue[900],
    link: gray[50],
    linkHover: gray[200],
    linkVisited: gray[300],
    focus: gray[50],
}

