import { neutralDark, neutralLight } from './shared'
import { indigo, cyan, gray, emerald, orange, red, blue, violet, white } from '../colors'

import type { BaseTheme } from '@/types'

type ColorPalette = BaseTheme['colors']

export const indigoLight: ColorPalette = {
    ...neutralLight,
    primary: indigo[500],
    onPrimary: white,
    primaryHover: indigo[600],
    primaryActive: indigo[700],
    primarySubtle: indigo[50],
    secondary: gray[500],
    onSecondary: white,
    secondaryHover: gray[600],
    secondaryActive: gray[700],
    secondarySubtle: gray[100],
    accent: cyan[500],
    onAccent: white,
    accentHover: cyan[600],
    accentSubtle: cyan[50],
    borderFocus: indigo[500],
    success: emerald[500],
    onSuccess: white,
    successHover: emerald[600],
    successSubtle: emerald[50],
    warning: orange[500],
    onWarning: white,
    warningHover: orange[600],
    warningSubtle: orange[50],
    error: red[500],
    onError: white,
    errorHover: red[600],
    errorSubtle: red[50],
    info: blue[500],
    onInfo: white,
    infoHover: blue[600],
    infoSubtle: blue[50],
    link: indigo[500],
    linkHover: indigo[600],
    linkVisited: violet[500],
    focus: indigo[500],
}

export const indigoDark: ColorPalette = {
    ...neutralDark,
    primary: indigo[400],
    onPrimary: indigo[950],
    primaryHover: indigo[300],
    primaryActive: indigo[500],
    primarySubtle: indigo[900],
    secondary: gray[400],
    onSecondary: gray[900],
    secondaryHover: gray[300],
    secondaryActive: gray[200],
    secondarySubtle: gray[800],
    accent: cyan[400],
    onAccent: cyan[950],
    accentHover: cyan[300],
    accentSubtle: cyan[900],
    borderFocus: indigo[400],
    success: emerald[400],
    onSuccess: emerald[950],
    successHover: emerald[300],
    successSubtle: emerald[900],
    warning: orange[400],
    onWarning: orange[950],
    warningHover: orange[300],
    warningSubtle: orange[900],
    error: red[400],
    onError: red[950],
    errorHover: red[300],
    errorSubtle: red[900],
    info: blue[400],
    onInfo: blue[950],
    infoHover: blue[300],
    infoSubtle: blue[900],
    link: indigo[400],
    linkHover: indigo[300],
    linkVisited: violet[400],
    focus: indigo[400],
}

