import { neutralDark, neutralLight } from './shared'
import { rose, violet, gray, emerald, amber, red, sky, purple, white } from '../colors'

import type { BaseTheme } from '@/types/Theme'

type ColorPalette = BaseTheme['colors']

export const roseLight: ColorPalette = {
    ...neutralLight,
    primary: rose[500],
    onPrimary: white,
    primaryHover: rose[600],
    primaryActive: rose[700],
    primarySubtle: rose[50],
    secondary: gray[500],
    onSecondary: white,
    secondaryHover: gray[600],
    secondaryActive: gray[700],
    secondarySubtle: gray[100],
    accent: violet[500],
    onAccent: white,
    accentHover: violet[600],
    accentSubtle: violet[50],
    borderFocus: rose[500],
    success: emerald[500],
    onSuccess: white,
    successHover: emerald[600],
    successSubtle: emerald[50],
    warning: amber[500],
    onWarning: white,
    warningHover: amber[600],
    warningSubtle: amber[50],
    error: red[500],
    onError: white,
    errorHover: red[600],
    errorSubtle: red[50],
    info: sky[500],
    onInfo: white,
    infoHover: sky[600],
    infoSubtle: sky[50],
    link: rose[500],
    linkHover: rose[600],
    linkVisited: purple[500],
    focus: rose[500],
}

export const roseDark: ColorPalette = {
    ...neutralDark,
    primary: rose[400],
    onPrimary: rose[950],
    primaryHover: rose[300],
    primaryActive: rose[500],
    primarySubtle: rose[900],
    secondary: gray[400],
    onSecondary: gray[900],
    secondaryHover: gray[300],
    secondaryActive: gray[200],
    secondarySubtle: gray[800],
    accent: violet[400],
    onAccent: violet[950],
    accentHover: violet[300],
    accentSubtle: violet[900],
    borderFocus: rose[400],
    success: emerald[400],
    onSuccess: emerald[950],
    successHover: emerald[300],
    successSubtle: emerald[900],
    warning: amber[400],
    onWarning: amber[950],
    warningHover: amber[300],
    warningSubtle: amber[900],
    error: red[400],
    onError: red[950],
    errorHover: red[300],
    errorSubtle: red[900],
    info: sky[400],
    onInfo: sky[950],
    infoHover: sky[300],
    infoSubtle: sky[900],
    link: rose[400],
    linkHover: rose[300],
    linkVisited: purple[400],
    focus: rose[400],
}

