import { neutralDark, neutralLight } from './shared'
import { slate, blue, emerald, amber, red, sky, white } from '../colors'

import type { BaseTheme } from '@/types'

type ColorPalette = BaseTheme['colors']

export const slateLight: ColorPalette = {
    ...neutralLight,
    primary: slate[600],
    onPrimary: white,
    primaryHover: slate[700],
    primaryActive: slate[800],
    primarySubtle: slate[100],
    secondary: slate[500],
    onSecondary: white,
    secondaryHover: slate[600],
    secondaryActive: slate[700],
    secondarySubtle: slate[100],
    accent: blue[500],
    onAccent: white,
    accentHover: blue[600],
    accentSubtle: blue[50],
    borderFocus: slate[600],
    success: emerald[500],
    onSuccess: white,
    successHover: emerald[600],
    successSubtle: emerald[50],
    warning: amber[500],
    onWarning: white,
    warningHover: amber[600],
    warningSubtle: amber[50],
    error: red[500],
    onError: white,
    errorHover: red[600],
    errorSubtle: red[50],
    info: sky[500],
    onInfo: white,
    infoHover: sky[600],
    infoSubtle: sky[50],
    link: slate[700],
    linkHover: slate[800],
    linkVisited: slate[600],
    focus: slate[600],
}

export const slateDark: ColorPalette = {
    ...neutralDark,
    primary: slate[300],
    onPrimary: slate[900],
    primaryHover: slate[200],
    primaryActive: slate[400],
    primarySubtle: slate[800],
    secondary: slate[400],
    onSecondary: slate[900],
    secondaryHover: slate[300],
    secondaryActive: slate[200],
    secondarySubtle: slate[800],
    accent: blue[400],
    onAccent: blue[950],
    accentHover: blue[300],
    accentSubtle: blue[900],
    borderFocus: slate[300],
    success: emerald[400],
    onSuccess: emerald[950],
    successHover: emerald[300],
    successSubtle: emerald[900],
    warning: amber[400],
    onWarning: amber[950],
    warningHover: amber[300],
    warningSubtle: amber[900],
    error: red[400],
    onError: red[950],
    errorHover: red[300],
    errorSubtle: red[900],
    info: sky[400],
    onInfo: sky[950],
    infoHover: sky[300],
    infoSubtle: sky[900],
    link: slate[300],
    linkHover: slate[200],
    linkVisited: slate[400],
    focus: slate[300],
}

