import { neutralDark, neutralLight } from './shared'
import { violet, pink, gray, emerald, amber, red, blue, purple, white } from '../colors'

import type { BaseTheme } from '@/types'

type ColorPalette = BaseTheme['colors']

export const violetLight: ColorPalette = {
    ...neutralLight,
    primary: violet[500],
    onPrimary: white,
    primaryHover: violet[600],
    primaryActive: violet[700],
    primarySubtle: violet[50],
    secondary: gray[500],
    onSecondary: white,
    secondaryHover: gray[600],
    secondaryActive: gray[700],
    secondarySubtle: gray[100],
    accent: pink[500],
    onAccent: white,
    accentHover: pink[600],
    accentSubtle: pink[50],
    borderFocus: violet[500],
    success: emerald[500],
    onSuccess: white,
    successHover: emerald[600],
    successSubtle: emerald[50],
    warning: amber[500],
    onWarning: white,
    warningHover: amber[600],
    warningSubtle: amber[50],
    error: red[500],
    onError: white,
    errorHover: red[600],
    errorSubtle: red[50],
    info: blue[500],
    onInfo: white,
    infoHover: blue[600],
    infoSubtle: blue[50],
    link: violet[500],
    linkHover: violet[600],
    linkVisited: purple[500],
    focus: violet[500],
}

export const violetDark: ColorPalette = {
    ...neutralDark,
    primary: violet[400],
    onPrimary: violet[950],
    primaryHover: violet[300],
    primaryActive: violet[500],
    primarySubtle: violet[900],
    secondary: gray[400],
    onSecondary: gray[900],
    secondaryHover: gray[300],
    secondaryActive: gray[200],
    secondarySubtle: gray[800],
    accent: pink[400],
    onAccent: pink[950],
    accentHover: pink[300],
    accentSubtle: pink[900],
    borderFocus: violet[400],
    success: emerald[400],
    onSuccess: emerald[950],
    successHover: emerald[300],
    successSubtle: emerald[900],
    warning: amber[400],
    onWarning: amber[950],
    warningHover: amber[300],
    warningSubtle: amber[900],
    error: red[400],
    onError: red[950],
    errorHover: red[300],
    errorSubtle: red[900],
    info: blue[400],
    onInfo: blue[950],
    infoHover: blue[300],
    infoSubtle: blue[900],
    link: violet[400],
    linkHover: violet[300],
    linkVisited: purple[400],
    focus: violet[400],
}

